server:
  port: 9999
spring:
  datasource:
    druid:
      master:
        # tcpRcvBuf/tcpSndBuf 缓冲区参数 rewriteBatchedStatements batchUpdate参数
        url: jdbc:mysql://192.168.2.103:6001/tool?characterEncoding=utf8&verifyServerCertificate=false&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: zh34864486
        # 开源 SQL 日志框架，在大多数情况下极大改善了可读性及调试工作
        driver-class-name: com.mysql.cj.jdbc.Driver
        max-active: 10
        max-wait: 600000
        # sql监控
        filters: stat
        # 检测池里连接的可用性 开启影响性能 默认false
        test-on-borrow: false
        # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除 默认true
        test-while-idle: true
        # 每30秒运行一次空闲连接回收器
        time-between-eviction-runs-millis: 30000
        # 检测语句
        validation-query: "select 1"
      slave:
        # tcpRcvBuf/tcpSndBuf 缓冲区参数 rewriteBatchedStatements batchUpdate参数
        url: jdbc:mysql://192.168.2.103:6002/tool?characterEncoding=utf8&verifyServerCertificate=false&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: zh34864486
        driver-class-name: com.mysql.cj.jdbc.Driver
        max-active: 10
        max-wait: 600000
        # sql监控
        filters: stat
        # 检测池里连接的可用性 开启影响性能 默认false
        test-on-borrow: false
        # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除 默认true
        test-while-idle: true
        # 每30秒运行一次空闲连接回收器
        time-between-eviction-runs-millis: 30000
        # 检测语句
        validation-query: "select 1"


  redis:
    cluster:
      nodes: 192.168.2.103:7001
    password: zh34864486
  config:
    activate:
      on-profile: home

myatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tiankong44.tool
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'


logging:
  level:
    root: info
    com.tiankong44.tool.mapper: debug

