server:
  port: 9999

#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      master:
#        username: root
#        password: zh34864486
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://xy.tiankong44.vip:6001/tool?characterEncoding=utf8&verifyServerCertificate=false&useSSL=true&serverTimezone=Asia/Shanghai
#      slave:
#        username: root
#        password: zh34864486
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://xy.tiankong44.vip:6002/tool?characterEncoding=utf8&verifyServerCertificate=false&useSSL=true&serverTimezone=Asia/Shanghai
#
#      # 初始连接数
#      initialSize: 5
#      # 最小连接池数量
#      minIdle: 10
#      # 最大连接池数量
#      maxActive: 20
#      # 配置获取连接等待超时的时间
#      maxWait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      # 配置一个连接在池中最大生存的时间，单位是毫秒
#      maxEvictableIdleTimeMillis: 900000
#      # 配置检测连接是否有效
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      webStatFilter:
#        enabled: true
#      statViewServlet:
#        enabled: true
#        # 设置白名单，不填则允许所有访问
#        allow:
#        url-pattern: /druid/*
#        # 控制台管理用户名和密码
#        login-username: admin
#        login-password: admin
#      filter:
#        stat:
#          enabled: true
#          # 慢SQL记录
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          merge-sql: true
#        wall:
#          config:
#            multi-statement-allow: true


spring:
  datasource:
    druid:
      master:
        # tcpRcvBuf/tcpSndBuf 缓冲区参数 rewriteBatchedStatements batchUpdate参数
        url: jdbc:mysql://xy.tiankong44.vip:6001/tool?characterEncoding=utf8&verifyServerCertificate=false&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: zh34864486
        # 开源 SQL 日志框架，在大多数情况下极大改善了可读性及调试工作
        driver-class-name: com.mysql.cj.jdbc.Driver
        max-active: 10
        max-wait: 600000
        # sql监控
        filters: stat
        # 检测池里连接的可用性 开启影响性能 默认false
        test-on-borrow: false
        # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除 默认true
        test-while-idle: true
        # 每30秒运行一次空闲连接回收器
        time-between-eviction-runs-millis: 30000
        # 检测语句
        validation-query: "select 1"
      slave:
        # tcpRcvBuf/tcpSndBuf 缓冲区参数 rewriteBatchedStatements batchUpdate参数
        url: jdbc:mysql://xy.tiankong44.vip:6002/tool?characterEncoding=utf8&verifyServerCertificate=false&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: zh34864486
        driver-class-name: com.mysql.cj.jdbc.Driver
        max-active: 10
        max-wait: 600000
        # sql监控
        filters: stat
        # 检测池里连接的可用性 开启影响性能 默认false
        test-on-borrow: false
        # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除 默认true
        test-while-idle: true
        # 每30秒运行一次空闲连接回收器
        time-between-eviction-runs-millis: 30000
        # 检测语句
        validation-query: "select 1"


  redis:
    #    cluster:
    #      nodes: 127.0.0.1:6379
    password: root
    host: localhost
    port: 6379

m atis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tiankong44.tool
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'


logging:
  level:
    root: info
    com.tiankong44.tool.mapper: debug

